services:
    api:
        build: ./api
        container_name: api
        restart: always
        ports:
            - '3000:3000'
        environment:
            - DATABASE_URL=${DATABASE_URL}
        volumes:
            - ./api:/usr/src/app

    frontend:
        build: ./frontend
        container_name: frontend
        restart: always
        ports:
            - '5173:5173'
        depends_on:
            - api
        environment:
            - VITE_AXIOS_BASE_URL=http://localhost:3000
        volumes:
            - ./frontend:/usr/src/app
