services:
    api:
        environment:
            - NODE_ENV=production
            - DATABASE_URL=${DATABASE_URL}
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: '512M'

    frontend:
        environment:
            - VITE_AXIOS_BASE_URL=${VITE_AXIOS_BASE_URL}
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '256M'
