services:
    api:
        build: ./api
        container_name: api
        restart: always
        ports:
            - '3000:3000'
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
            - CLERK_WEBHOOK_SECRET=${CLERK_WEBHOOK_SECRET}
            - CLERK_WEBHOOK_SECRET=${CLERK_WEBHOOK_SECRET}
            - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
            - NGROK_URL=${NGROK_URL}
        volumes:
            - ./api:/usr/src/app

    frontend:
        build: ./frontend
        container_name: frontend
        restart: always
        ports:
            - '5173:5173'
        depends_on:
            - api
        environment:
            - VITE_AXIOS_BASE_URL=http://localhost:3000
            - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
        volumes:
            - ./frontend:/usr/src/app
