FROM node:22.0.0

WORKDIR /usr/src/app

COPY package*.json ./

RUN apt-get update && apt-get install -y \
    wget \
    gnupg2 \
    lsb-release \
    && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
    && echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && apt-get update \
    && apt-get install -y postgresql-client-17 \
    && rm -rf /var/lib/apt/lists/*

COPY . .

EXPOSE 3000

CMD [ "npm", "run", "dev" ]