FROM node:22.0.0-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=production

RUN npm install

COPY . .

RUN npx prisma generate

ENV NODE_ENV=production

EXPOSE 3000

CMD [ "npm", "run", "start" ]