name: Node.js CI

on:
    push:
        branches: ['dev']
    pull_request:
        branches: ['dev']

jobs:
    # Build job
    build:
        runs-on: ubuntu-latest

        steps:
            # Checkout the code from the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22.x

            # Install Docker Compose
            - name: Install Docker Compose
              run: |
                  sudo apt-get update
                  sudo apt-get install -y docker-compose

            # Install all dependencies
            - name: Install all dependencies
              run: npm run install:all

            # Start Docker Compose services
            - name: Start Docker Compose
              run: |
                  docker-compose up -d db
                  docker-compose up -d api

            # Wait for services to be ready
            - name: Wait for API to be ready
              run: |
                  SECONDS=0
                  until curl -s http://localhost:3000/health || [ $SECONDS -gt 30 ]; do
                    sleep 1
                  done

    # Test job
    test-api:
        runs-on: ubuntu-latest
        needs: build

        steps:
            # Checkout the code from the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Install dependencies for the API
            - name: Install API dependencies
              run: npm install --prefix ./api

            # Run tests
            - name: Run API tests
              run: npm run test:api
